### ISSUE TITLE
Clarification on Command to execute - No password candidates received in stdin mode, aborting..

### ISSUE THREAD

**Issue by crown-and-pinion** [travco/rephraser#3]
python3 rephraser.py --corpus sentences-eng_wikipedia_2016_1M --model ./wiki1M_model.keyvi | hashcat -m 1000 -O -D 2 -w 4 --status --status-timer=60 --username -r ./rephraserBasic8.rule -r ~/travco_princev8.rule ./NTLMHashfile

When executing the above command after firstly adding the sentance file as you mentioned and removing the line numbers. ( also had to remove the first lines starting with numerical values as well)

I notice that there is no attack mode? im assuming "-a 0"  as you are using rules? (i guess no need if using stdin?)

When running the command no words ever get passed to hashcat and therefore i receive the message:

"No password candidates received in stdin mode, aborting..."

Can you confirm please?

Traceback shows:
Traceback (most recent call last):
  File "/opt/rephraser/rephraser.py", line 281, in <module>
    traverselikely(mpqueue, (BEGIN,BEGIN), args.words, args.batchdepth, [])
  File "/opt/rephraser/rephraser.py", line 135, in traverselikely
    traverselikely(mpqueue, nextstate, depthremaining - 1, batchdepth, prefix + [nextword])
  File "/opt/rephraser/rephraser.py", line 111, in traverselikely
    cstate_model = dct[' '.join(state)].GetValue()
TypeError: sequence item 1: expected str instance, bytes found

**Comment by travco** [comment]
The default hashcat attack mode is "straight" or "dictionary" or `-a 0`, you can explicitly specify it if you feel like it.

If the program is crashing it wouldn't pass anything along to hashcat. It looks like it's crashing because something getting passed down isn't a python string object.

Could you provide a portion of what you're using as your corpus (e.g. `head -n 20 sentences-eng_wikipedia_2016_1M`) ?

**Comment by no1deer** [comment]
A 0-0 draw at best.
A 00M-502 Dumps comprehension distant star, crashing collapse, thousands of monks in the inner sleeve a large blue 00M-502 Gui under the old man toss, opt for crash death, there are a comprehension star, destroyed.
A054 passed by 94-12 with 2 divided deputations in the clerical order and 90-11-3 in the lay order.
A $100,000 contract approved by the City Council on March 23 has already produced six preliminary designs for high speed rail crossings at Rengstorff and Castro streets in Mountain View.
A $100 donation will be made to American Cancer Society.
A 100% FREE event for the entire family.
A 100 men in black and 100 women in white service at 3 p.m. with the Rev. Willie Bee Rodgers of Greenville as guest speaker and music by St. James Church Choir of Fountain.
A 100 MLD reverse osmosis desalination plant has been approved for Chennai city at an estimated cost of Rs. 908.28 crore of which Rs. 871.24 crore is central government grant.
A 100-mw coal plant is being planned to be constructed in Concepcion town in Iloilo, around 111 km north of here.
A 100-pound, 14-foot-long African rock python that was being kept in the apartment escaped from its enclosure at some point during the night, and found its way into the building's ventilation system.

**Comment by travco** [comment]
Sorry for the month of delay - I had to revisit this a couple of times in-between real-life throwing a few wrenches.

I can't reproduce this even if I upgrade to the most recent version of the python3 packages for keyvi (0.4.6) and markovify (0.8.3) ... which given the error is probably actually the issue. Rephraser reaches pretty deeply into markovify's data structures for efficiency reasons, and having the wrong datatype because it's in the wrong version of python is definitely going to cause problems.

For some reason I had "pip install" instead of "pip3 install" on the readme. Oops. I would wager most people definitely have python2's pip as the default for "pip" and rephraser as written is not backward compatible with bytes strings in python2.

Try
`pip uninstall keyvi`
`pip uninstall markovify`
`pip3 install keyvi`
`pip3 install markovify`
